### Artificial Neural Network

In [1]:
from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
import scipy as sp
import seaborn as sns
import matplotlib as mp
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
url_raw = './Dataset/development_dataset.csv'
url_train = 'itrImputed_NoOut_CB.csv' #traing dataset
url_dict = './Dataset/Data_Dictionary.xlsx' #data dictionary
url_lead = 'itrImputedlead.csv' 
url_lead_raw = './Dataset/leaderboard_dataset.csv'

In [3]:
## making dataframe
df_raw = pd.read_csv(url_raw)
df_train = pd.read_csv(url_train)
df_dict = pd.read_excel(url_dict)
df_lead = pd.read_csv(url_lead)
df_lead_raw = pd.read_csv(url_lead_raw)

In [4]:
df_train.head()

Unnamed: 0    0    1           2         3           4           5  \
0           0  0.0  1.0  828.235294  0.138889  321.428571  625.911006   
1           1  1.0  2.0  911.764706  0.027778  238.761364  611.574748   
2           2  2.0  3.0  962.352941  0.833333   35.714286  615.825381   
3           3  3.0  4.0  892.941177  0.782091  233.617604  638.076431   
4           4  4.0  5.0  914.117647  0.083333  196.574005  626.514988   

          6         7           8  ...          12         13        14  \
0  1.818182  1.081550  198.113469  ...  100.083403   1.000000  1.000000   
1  8.181818  1.344479  198.600020  ...   15.012510  11.050880  1.000000   
2  8.181818  0.720796  197.267767  ...  210.175146  10.000000  1.000000   
3  9.090909  0.820218  197.355744  ...  134.651887   9.612582  1.000000   
4  5.181818  1.372928  198.790477  ...  210.175146  11.549667  1.258089   

          15        16          17   18   19          20   class  
0   1.000000  1.540594  859.508022  1.0  0.0  100.104991     Low  
1  11.776264  1.614613  869.487400  0.0  1.0  146.654045    High  
2  10.000000  1.044599  728.127337  0.0  0.0   98.249570  Medium  
3  10.163069  1.145729  929.978034  1.0  0.0  140.862306     Low  
4  12.494794  1.558341  720.948316  1.0  0.0  101.268503    High  

[5 rows x 23 columns]

In [5]:
X = df_train.iloc[:, 3:-1].values
y = df_train.iloc[:, 22].values

#X_lead = df_lead.iloc[:, 2:].values
#X_lead_raw = df_lead_raw.iloc[:, 1:].values

#X_raw = df_raw.iloc[:, 1:-1].values
#y_raw = df_raw.iloc[:, 20].values

In [13]:
X.shape

(37572, 19)

In [9]:
y

array(['Low', 'High', 'Medium', ..., 'Low', 'Low', 'Low'], dtype=object)

In [10]:
# label Encoding
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_X = LabelEncoder()
#X[:, 11] = labelencoder_X.fit_transform(X[:, 11])

labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

In [11]:
y

array([1, 0, 2, ..., 1, 1, 1])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
# X_train = sc_X.fit_transform(X_train)
# X_test = sc_X.transform(X_test)
#X_lead = sc_X.transform(X_lead)
#X_oth = sc_X.fit_transform(X_oth)
#sc_y = StandardScaler()
#y_train = sc_y.fit_transform(y_train.reshape(-1,1))

In [12]:
# split data into train and test sets
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=seed)

#### Neural Network Architecture

In [14]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [15]:
#!pip install keras

In [16]:
# Initialising the ANN
classifier = Sequential()

In [17]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 19, init = 'uniform', activation = 'relu', input_dim = 19))
   
# Adding the second hidden layer
classifier.add(Dense(output_dim = 10, init = 'uniform', activation = 'relu'))

# Adding the third hidden layer
classifier.add(Dense(output_dim = 10, init = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

C:\Users\PASHUPATI-PC\Anaconda3\envs\ml\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=19, units=19, kernel_initializer="uniform")`
  


Instructions for updating:
Colocations handled automatically by placer.


C:\Users\PASHUPATI-PC\Anaconda3\envs\ml\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=10, kernel_initializer="uniform")`
  """
C:\Users\PASHUPATI-PC\Anaconda3\envs\ml\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=10, kernel_initializer="uniform")`
  
C:\Users\PASHUPATI-PC\Anaconda3\envs\ml\lib\site-packages\ipykernel_launcher.py:11: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  # This is added back by InteractiveShellApp.init_path()


In [18]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

##### Training ANN

In [19]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 50, nb_epoch = 500)

C:\Users\PASHUPATI-PC\Anaconda3\envs\ml\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Instructions for updating:
Use tf.cast instead.
Epoch 1/500
30057/30057 [==============================] - 2s 65us/step - loss: 0.1238 - accuracy: 0.3272
Epoch 2/500
30057/30057 [==============================] - 1s 37us/step - loss: 0.0538 - accuracy: 0.3272
Epoch 3/500
30057/30057 [==============================] - 1s 33us/step - loss: -0.0430 - accuracy: 0.3272
Epoch 4/500
30057/30057 [==============================] - 1s 37us/step - loss: -0.0985 - accuracy: 0.3272
Epoch 5/500
30057/30057 [==============================] - 1s 40us/step - loss: -0.1651 - accuracy: 0.3272
Epoch 6/500
30057/30057 [==============================] - 1s 34us/step - loss: -0.2225 - accuracy: 0.3272
Epoch 7/500
30057/30057 [==============================] - 1s 34us/step - loss: -0.2867 - accuracy: 0.3272
Epoch 8/500
30057/30057 [==============================] - 1s 33us/step - loss: -0.3366 - accuracy: 0.3272
Epoch 9/500
30057/30057 [==============================] - 1s 49us/step - loss: -0.3664 - accuracy

30057/30057 [==============================] - 1s 41us/step - loss: -0.6762 - accuracy: 0.3272
Epoch 74/500
30057/30057 [==============================] - 1s 45us/step - loss: -0.6848 - accuracy: 0.3272
Epoch 75/500
30057/30057 [==============================] - 1s 33us/step - loss: -0.6824 - accuracy: 0.3272
Epoch 76/500
30057/30057 [==============================] - 1s 34us/step - loss: -0.7159 - accuracy: 0.3272
Epoch 77/500
30057/30057 [==============================] - 1s 36us/step - loss: -0.7705 - accuracy: 0.3272
Epoch 78/500
30057/30057 [==============================] - 1s 34us/step - loss: -0.7261 - accuracy: 0.3272
Epoch 79/500
30057/30057 [==============================] - 1s 41us/step - loss: -0.7501 - accuracy: 0.3272
Epoch 80/500
30057/30057 [==============================] - 1s 47us/step - loss: -0.7532 - accuracy: 0.3272
Epoch 81/500
30057/30057 [==============================] - 1s 50us/step - loss: -0.7608 - accuracy: 0.3272
Epoch 82/500
30057/30057 [===============

30057/30057 [==============================] - 1s 33us/step - loss: -0.7086 - accuracy: 0.3272
Epoch 149/500
30057/30057 [==============================] - 1s 37us/step - loss: -0.8365 - accuracy: 0.3272
Epoch 150/500
30057/30057 [==============================] - 1s 35us/step - loss: -0.7978 - accuracy: 0.3272
Epoch 151/500
30057/30057 [==============================] - 1s 35us/step - loss: -0.8325 - accuracy: 0.3272
Epoch 152/500
30057/30057 [==============================] - 1s 34us/step - loss: -0.8685 - accuracy: 0.3272
Epoch 153/500
30057/30057 [==============================] - 1s 33us/step - loss: -0.8337 - accuracy: 0.3272
Epoch 154/500
30057/30057 [==============================] - 1s 37us/step - loss: -0.7970 - accuracy: 0.3272
Epoch 155/500
30057/30057 [==============================] - 1s 38us/step - loss: -0.8214 - accuracy: 0.3272
Epoch 156/500
30057/30057 [==============================] - 1s 32us/step - loss: -0.7708 - accuracy: 0.3272
Epoch 157/500
30057/30057 [======

30057/30057 [==============================] - 1s 40us/step - loss: -0.8884 - accuracy: 0.3272
Epoch 224/500
30057/30057 [==============================] - 1s 38us/step - loss: -0.8064 - accuracy: 0.3272
Epoch 225/500
30057/30057 [==============================] - 1s 43us/step - loss: -0.8308 - accuracy: 0.3272
Epoch 226/500
30057/30057 [==============================] - 1s 42us/step - loss: -0.8506 - accuracy: 0.3272
Epoch 227/500
30057/30057 [==============================] - 1s 35us/step - loss: -0.8669 - accuracy: 0.3272
Epoch 228/500
30057/30057 [==============================] - 1s 33us/step - loss: -0.8915 - accuracy: 0.3272
Epoch 229/500
30057/30057 [==============================] - 1s 31us/step - loss: -0.8519 - accuracy: 0.3272
Epoch 230/500
30057/30057 [==============================] - 1s 36us/step - loss: -0.8252 - accuracy: 0.3272
Epoch 231/500
30057/30057 [==============================] - 1s 36us/step - loss: -0.8468 - accuracy: 0.3272
Epoch 232/500
30057/30057 [======

30057/30057 [==============================] - 1s 37us/step - loss: -0.8992 - accuracy: 0.3272
Epoch 298/500
30057/30057 [==============================] - 1s 37us/step - loss: -0.8873 - accuracy: 0.3272
Epoch 299/500
30057/30057 [==============================] - 1s 40us/step - loss: -0.8056 - accuracy: 0.3272
Epoch 300/500
30057/30057 [==============================] - 1s 40us/step - loss: -0.8696 - accuracy: 0.3272
Epoch 301/500
30057/30057 [==============================] - 1s 35us/step - loss: -0.8269 - accuracy: 0.3272
Epoch 302/500
30057/30057 [==============================] - 1s 38us/step - loss: -0.8064 - accuracy: 0.3272
Epoch 303/500
30057/30057 [==============================] - 1s 33us/step - loss: -0.8625 - accuracy: 0.3272: 0s - loss: -0.9770 
Epoch 304/500
30057/30057 [==============================] - 1s 33us/step - loss: -0.8351 - accuracy: 0.3272
Epoch 305/500
30057/30057 [==============================] - 1s 34us/step - loss: -0.8567 - accuracy: 0.3272
Epoch 306/50

30057/30057 [==============================] - 1s 43us/step - loss: -0.9297 - accuracy: 0.3272
Epoch 372/500
30057/30057 [==============================] - 1s 40us/step - loss: -0.9444 - accuracy: 0.3272
Epoch 373/500
30057/30057 [==============================] - 1s 39us/step - loss: -0.9185 - accuracy: 0.3272
Epoch 374/500
30057/30057 [==============================] - 1s 40us/step - loss: -0.9114 - accuracy: 0.3272
Epoch 375/500
30057/30057 [==============================] - 1s 40us/step - loss: -0.9173 - accuracy: 0.3272
Epoch 376/500
30057/30057 [==============================] - 1s 44us/step - loss: -0.9369 - accuracy: 0.3272
Epoch 377/500
30057/30057 [==============================] - 2s 55us/step - loss: -0.8880 - accuracy: 0.3272
Epoch 378/500
30057/30057 [==============================] - 1s 42us/step - loss: -0.9322 - accuracy: 0.3272
Epoch 379/500
30057/30057 [==============================] - 1s 46us/step - loss: -0.8829 - accuracy: 0.3272
Epoch 380/500
30057/30057 [======

30057/30057 [==============================] - 1s 32us/step - loss: -0.8973 - accuracy: 0.3272
Epoch 446/500
30057/30057 [==============================] - 1s 34us/step - loss: -0.9370 - accuracy: 0.3272
Epoch 447/500
30057/30057 [==============================] - 1s 38us/step - loss: -0.9632 - accuracy: 0.3272
Epoch 448/500
30057/30057 [==============================] - 1s 42us/step - loss: -0.9521 - accuracy: 0.3272
Epoch 449/500
30057/30057 [==============================] - 1s 37us/step - loss: -0.9176 - accuracy: 0.3272
Epoch 450/500
30057/30057 [==============================] - 1s 31us/step - loss: -0.9193 - accuracy: 0.3272
Epoch 451/500
30057/30057 [==============================] - 1s 31us/step - loss: -0.9256 - accuracy: 0.3272
Epoch 452/500
30057/30057 [==============================] - 1s 41us/step - loss: -0.8964 - accuracy: 0.3272
Epoch 453/500
30057/30057 [==============================] - 1s 42us/step - loss: -0.8870 - accuracy: 0.3272
Epoch 454/500
30057/30057 [======

##### Evaluation ANN

In [23]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [24]:
y_pred

array([[ True],
       [ True],
       [ True],
       ...,
       [ True],
       [ True],
       [ True]])

In [26]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[   0, 2631,    0],
       [   0, 2460,    0],
       [   0, 2424,    0]], dtype=int64)